### ISSUE TITLE
Database log backup fails when some database is in middle of a restore 

### ISSUE THREAD

**Issue by JanneIlonen** [olahallengren/sql-server-maintenance-solution#270] opened 2019-08-28 11:46 UTC
Database log backup fails when some database is in middle of a restore 

**SQL Server version and edition**
Microsoft SQL Server 2017 (RTM-CU12) (KB4464082) - 14.0.3045.24 (X64)   Oct 18 2018 23:11:05   Copyright (C) 2017 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor) 

**Version of the script**
--// Version: 2018-06-27 20:44:12  

**What command are you executing?**
sqlcmd -E -S $(ESCAPE_SQUOTE(SRVR)) -d MaintenanceSolution -Q "EXECUTE [dbo].[DatabaseBackup] @Databases = 'USER_DATABASES', @Directory = N'R:\Backup\', @BackupType = 'LOG', @CleanupTime = 4, @CheckSum = 'Y', @LogToTable = 'Y'" -b

**What output are you getting?**
Msg 927, Level 14, State 6, Server TESTSQL, Line 1
Database 'MDS' cannot be opened. It is in the middle of a restore.

**Comment by olahallengren** [comment] 2019-12-25 21:08
What was the state in the database information in the output showing?

**Comment by JanneIlonen** [comment] 2019-12-27 08:01
**Errorlog**:

2019-12-23 19:15:13.86 spid210     Starting up database 'MDS'.
2019-12-23 19:15:13.94 spid210     Parallel redo is started for database 'MDS' with worker pool size [3].
2019-12-23 19:15:13.95 spid210     1 transactions rolled forward in database 'MDS' (7:0). This is an informational message only. No user action is required.
2019-12-23 19:15:13.98 spid210     0 transactions rolled back in database 'MDS' (7:0). This is an informational message only. No user action is required.
2019-12-23 19:15:13.99 spid210     Parallel redo is shutdown for database 'MDS' with worker pool size [3].
2019-12-23 19:15:14.14 spid210     CHECKDB for database 'MDS' finished without errors on 2017-07-08 06:48:41.473 (local time). This is an informational message only; no user action is required.
2019-12-23 19:15:17.43 spid210     Synchronize Database 'MDS' (7) with Resource Database.
2019-12-23 19:15:17.50 Backup      Restore is complete on database 'MDS'.  The database is now available.


**DatabaseBackup - USER_DATABASES - LOG**:

Date and time: 2019-12-23 19:15:15
Database: [DB1]
Status: ONLINE
Standby: No
Updateability: READ_WRITE
User access: MULTI_USER
Is accessible: Yes
Recovery model: SIMPLE
Encrypted: No
Differential base LSN: 686000001293700163
Last log backup LSN: N/A
Last log backup: 1900-01-01 00:00:00
Log size since last log backup (MB): N/A
 
Msg 927, Level 14, State 6, Server TESTSQL01, Line 1
Database 'MDS' cannot be opened. It is in the middle of a restore.

**Comment by olahallengren** [comment] 2019-12-27 11:07
In the error log it says MDS, but in the output it says DB1. Is that correct?

**Comment by JanneIlonen** [comment] 2019-12-27 11:23
There is only 2 lines from MDS database. DB1 is different database.

**Comment by olahallengren** [comment] 2019-12-27 13:37
So this looks like you are getting an error about MDS, when the stored procedure is working on DB1. Would it be possible for you to attach the complete output - file? You can also send it to me in a mail, if you prefer that.

**Comment by olahallengren** [comment] 2019-12-31 16:13
I have tried to reproduce this issue.

I am restoring a database, and then I start a log backup. It skips the database that is being restored (State: RESTORING), and performs a log backup of the other databases successfully.

Can you reproduce the issue consistently?

**Comment by olahallengren** [comment] 2020-01-26 11:41
I have improved the logging in DatabaseBackup.

I am still not able to reproduce the issue.  If anyone is running into this issue, please report it here.

**Comment by olahallengren** [comment] 2024-11-23 18:23
I am closing this issue, as I am not able to reproduce it.

**Closed by olahallengren** 2024-11-23 18:23 UTC
Labels: DatabaseBackup, Bug Report, Not able to reproduce
