### ISSUE TITLE
Transaction Log Backup

### ISSUE THREAD

**Issue by sitrl** [olahallengren/sql-server-maintenance-solution#286] opened 2019-09-23 15:10 UTC
Transaction Log Backup with OLA script

Dump generation and Microsoft confirm Ola script's bug.

Thanks for your confirmation , I have checked with the escalation team for the reason of the dump and it was confirmed the Ola’s scripts run sys. dm_db_file_space_usage  at parallel with the log backup and this causes dump file .

Script Version

**SQL Server version and edition**
Microsoft SQL Server 2016 (SP2-CU8) (KB4505830) - 13.0.5426.0 (X64)   Jul 21 2019 21:16:47   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) (Hypervisor) 

**Version of the script**
/****** Object:  StoredProcedure [dbo].[DatabaseBackup]    Script Date: 23.09.2019 17:09:13 ******/

**What command are you executing?**
EXECUTE [dbo].[DatabaseBackup]
@Databases = 'USER_DATABASES',
@Directory = NULL,
@BackupType = 'LOG',
@Verify = 'Y',
@CleanupTime = NULL,
@CheckSum = 'Y',
@LogToTable = 'Y'
**What output are you getting?**
Core Dump attached
[SQLDump0023.log](https://github.com/olahallengren/sql-server-maintenance-solution/files/3642796/SQLDump0023.log)
[SQLDump0023.txt](https://github.com/olahallengren/sql-server-maintenance-solution/files/3642797/SQLDump0023.txt)

**Comment by sitrl** [comment] 2019-09-23 15:11
[SQLDump0023.zip](https://github.com/olahallengren/sql-server-maintenance-solution/files/3642804/SQLDump0023.zip)

Core dump

**Comment by reharmsen** [comment] 2019-09-25 09:19
Are you sure this is something that has to be fixed in the stored procedure?
I would thing Microsoft should fix this in de SQL Server code.

We are running SQL 2016 SP2-CU7, and I haven't seen any of these dumps

**Comment by sitrl** [comment] 2019-09-26 05:32
Hi,
yes confirm that is a Ola Scripts bug.

Microsoft email:


Hello Lorenzo ,

…

Yes , we are sure it’s a known issue Ola backup script .

Thanks for your time have a nice day .


Best Regards,

Ahmad Hassan Helmy

SQL Support
SQL Core
Customer Services and Support

Office: +20 (2) 35393323
v-ahhas@microsoft.com<mailto:v-ahhas@microsoft.com>
Working hours: Sun – Thu (9:00 - 18:00 GMT+2)

[Microsoft]


Da: Robin Harmsen <notifications@github.com>
Inviato: mercoledì, 25 settembre 2019 11:19
A: olahallengren/sql-server-maintenance-solution <sql-server-maintenance-solution@noreply.github.com>
Cc: Trenta Lorenzo <Lorenzo.Trenta@ti.ch>; State change <state_change@noreply.github.com>
Oggetto: Re: [olahallengren/sql-server-maintenance-solution] Transaction Log Backup (#286)


Are you sure this is something that has to be fixed in the stored procedure?
I would thing Microsoft should fix this in de SQL Server code.

We are running SQL 2016 SP2-CU7, and I haven't seen any of these dumps

**Comment by sitrl** [comment] 2019-09-26 05:42
For more information, please refer to the following topics:

Microsoft Support Case ID: [REG:119091122000373] During a Transaction Log Backup Sql Server has generated a Core Dump and the database has changed on Emergency Mode (Read only availability).
Contact: Ahmad Hassan Helmy - v-ahhas@microsoft.com<mailto:v-ahhas@microsoft.com>

Let me known.

Best regards.

Lorenzo

Da: Trenta Lorenzo
Inviato: giovedì, 26 settembre 2019 07:33
A: 'olahallengren/sql-server-maintenance-solution' <reply@reply.github.com>; olahallengren/sql-server-maintenance-solution <sql-server-maintenance-solution@noreply.github.com>
Cc: State change <state_change@noreply.github.com>
Oggetto: R: [olahallengren/sql-server-maintenance-solution] Transaction Log Backup (#286)
Priorità: Alta

Hi,
yes confirm that is a Ola Scripts bug.

Microsoft email:


Hello Lorenzo ,

…

Yes , we are sure it’s a known issue Ola backup script .

Thanks for your time have a nice day .


Best Regards,

Ahmad Hassan Helmy

SQL Support
SQL Core
Customer Services and Support

Office: +20 (2) 35393323
v-ahhas@microsoft.com<mailto:v-ahhas@microsoft.com>
Working hours: Sun – Thu (9:00 - 18:00 GMT+2)

[Microsoft]


Da: Robin Harmsen <notifications@github.com<mailto:notifications@github.com>>
Inviato: mercoledì, 25 settembre 2019 11:19
A: olahallengren/sql-server-maintenance-solution <sql-server-maintenance-solution@noreply.github.com<mailto:sql-server-maintenance-solution@noreply.github.com>>
Cc: Trenta Lorenzo <Lorenzo.Trenta@ti.ch<mailto:Lorenzo.Trenta@ti.ch>>; State change <state_change@noreply.github.com<mailto:state_change@noreply.github.com>>
Oggetto: Re: [olahallengren/sql-server-maintenance-solution] Transaction Log Backup (#286)


Are you sure this is something that has to be fixed in the stored procedure?
I would thing Microsoft should fix this in de SQL Server code.

We are running SQL 2016 SP2-CU7, and I haven't seen any of these dumps

**Comment by olahallengren** [comment] 2019-09-29 13:36
Could you post the summary from the support case?

I can't see how this could be an issue in my script. I am only using the native backup command, and DMVs. That should not cause stack dumps. I think that it looks like a bug in SQL Server.

**Comment by sitrl** [comment] 2019-09-30 08:45
Best Regards,       Ahmad Hassan Helmy
--
SQL Support   SQL Core   Customer Services and Support | Office: +20 (2) 35393323   v-ahhas@microsoft.com   Working hours: Sun – Thu (9:00 - 18:00 GMT+2) |

**Comment by sitrl** [comment] 2019-09-30 08:48
Hello Lorenzo , 

Thanks for your confirmation , I have checked with the escalation team for the reason of the dump and it was confirmed the Ola’s scripts run sys. dm_db_file_space_usage  at parallel with the log backup and this causes dump file .

If the issue is not reoccurring you can safely ignore the dump generated or if you would like to avoid in the future you can use built-in SQL maintenance plans for log backup .

Please let me know if you have any further questions , I will be more than happy to help .

Best Regards,

Ahmad Hassan Helmy

**Comment by sitrl** [comment] 2019-09-30 08:48
Hello Lorenzo , 

I will keep it open till end of Thursday 26th .

Yes , we are sure it’s a known issue Ola backup script .

Thanks for your time have a nice day .

**Comment by olahallengren** [comment] 2019-09-30 17:36
@sitrl, could I ask you to send me a mail.

**Comment by sitrl** [comment] 2019-10-01 06:54
Hi,
Microsoft has closed the Case Support.
On Yellow the Cause.

I am not happy.

Lorenzo


It was my pleasure to work with you on this issue .

As communicated previously this case will be temporarily archived . If you have further problems within the scope of this issue, please do reopen the support case.

You may receive an invitation from Microsoft to complete a brief web survey. Your feedback is very important to us and we use it to continually improve our service. We would appreciate it if you can take the time to complete this survey. In addition, if you would like to discuss any feedback you can also contact me directly or my manager using the contact information below.

Below is a summary of the case for your records:

Symptom:    SQL Server Stack Dump created while tlog backup

Cause:     Customer is using Ola Hallengreen script for log backup , Ola’s scripts run sys. dm_db_file_space_usage  at parallel and this causes dump file , The issue still under investigation by the product team .

Resolution: Customer moved the database to another instance , changed the database to simple .


Da: Ola Hallengren <notifications@github.com>
Inviato: lunedì, 30 settembre 2019 19:37
A: olahallengren/sql-server-maintenance-solution <sql-server-maintenance-solution@noreply.github.com>
Cc: Trenta Lorenzo <Lorenzo.Trenta@ti.ch>; Mention <mention@noreply.github.com>
Oggetto: Re: [olahallengren/sql-server-maintenance-solution] Transaction Log Backup (#286)


@sitrl<https://github.com/sitrl>, could I ask you to send me a mail.

**Comment by olahallengren** [comment] 2019-12-26 15:49
@sitrl, could you try installing the latest CU and see if you are able to reproduce the issue.

**Comment by sitrl** [comment] 2019-12-27 08:41
Hi,
I have disabled the Checksum parameter and now run without any issues.

Example:

EXECUTE [dbo].[DatabaseBackup]
@Databases = 'USER_DATABASES',
@Directory = NULL,
@BackupType = 'LOG',
@Verify = 'Y',
@CleanupTime = NULL,
@CheckSum = 'N',
@LogToTable = 'Y'

Regards.

Lorenzo

Da: Ola Hallengren <notifications@github.com>
Inviato: giovedì, 26 dicembre 2019 16:49
A: olahallengren/sql-server-maintenance-solution <sql-server-maintenance-solution@noreply.github.com>
Cc: Trenta Lorenzo <Lorenzo.Trenta@ti.ch>; Mention <mention@noreply.github.com>
Oggetto: Re: [olahallengren/sql-server-maintenance-solution] Transaction Log Backup (#286)


@sitrl<https://github.com/sitrl>, could you try installing the latest CU and see if you are able to reproduce the issue.

**Comment by olahallengren** [comment] 2019-12-27 11:03
What happens if you run with the Checksum parameter? Are you getting a stack dump then?

**Comment by sitrl** [comment] 2019-12-27 12:41
Generated a Core Dump of Sql Server … attached.

Da: Ola Hallengren <notifications@github.com>
Inviato: venerdì, 27 dicembre 2019 12:04
A: olahallengren/sql-server-maintenance-solution <sql-server-maintenance-solution@noreply.github.com>
Cc: Trenta Lorenzo <Lorenzo.Trenta@ti.ch>; Mention <mention@noreply.github.com>
Oggetto: Re: [olahallengren/sql-server-maintenance-solution] Transaction Log Backup (#286)


What happens if you run with the Checksum parameter? Are you getting a stack dump then?

**Comment by olahallengren** [comment] 2019-12-27 13:34
Does this happen only for one database, or does the same happen for all databases?

**Comment by sitrl** [comment] 2019-12-27 13:48
Hi,
once one.

Da: Ola Hallengren <notifications@github.com>
Inviato: venerdì, 27 dicembre 2019 14:34
A: olahallengren/sql-server-maintenance-solution <sql-server-maintenance-solution@noreply.github.com>
Cc: Trenta Lorenzo <Lorenzo.Trenta@ti.ch>; Mention <mention@noreply.github.com>
Oggetto: Re: [olahallengren/sql-server-maintenance-solution] Transaction Log Backup (#286)


Does this happen only for one database, or does the same happen for all databases?

**Comment by trel30** [comment] 2020-11-16 08:34
SOLVED: moved the database to another instance

**Comment by olahallengren** [comment] 2020-11-16 09:36
@trel30, thank you for the update. This is very good.

I can also confirm that Microsoft has fixed this issue in SQL Server 2016 SP2 CU13.
https://support.microsoft.com/en-us/help/4549825/kb4549825-cumulative-update-13-for-sql-server-2016-sp2


13517385 |   | Assertion exception or Access Violation occurs when you query sys.dm_db_file_space_usage dmv in SQL Server 2016 | SQL Engine | Windows
-- | -- | -- | -- | --

**Closed by olahallengren** 2020-11-16 09:36 UTC
Labels: DatabaseBackup, SQL Server Bug
