### ISSUE TITLE
Duplicate \ in folder path when using root folder

### ISSUE THREAD

**Issue by Timbleweed** [olahallengren/sql-server-maintenance-solution#404] opened 2020-07-20 14:04 UTC
**Description of the issue**

**SQL Server version and edition**
Microsoft SQL Server 2016 (SP2-CU12) (KB4536648) - 13.0.5698.0 (X64)   Feb 15 2020 01:47:30   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor) 

**Version of the script**
Version: 2020-01-26 14:06:53

**What command are you executing?**
EXEC dbo.DatabaseBackup @Databases = 'GValley' 
	, @Directory = '\\AH-LVD-Synology\CORE-to-Analytics\'
	, @DirectoryStructure = '\'
	, @BackupType = 'FULL'
	,@Compress = 'Y'
	, @Init = 'Y'
	, @NumberOfFiles = 4
	, @Description = 'CORE to Analytics Backup Copy'
	, @FileName = '{DatabaseName}_{BackupType}_{FileNumber}.{FileExtension}'
	, @Execute = 'Y'
	, @LogToTable = 'Y'

**What output are you getting?**
Location error has duplicate \ in path   '\\AH-LVD-Synology\CORE-to-Analytics\\GValley'

**Comment by Timbleweed** [comment] 2020-07-20 14:05
Command is as follows, not sure why copy past didn't work
EXEC dbo.DatabaseBackup @Databases = 'GValley' 
	, @Directory = '\\AH-LVD-Synology\CORE-to-Analytics\'
	, @DirectoryStructure = '\'  -- this is \
	, @BackupType = 'FULL'
	,@Compress = 'Y'
	, @Init = 'Y'
	, @NumberOfFiles = 4
	, @Description = 'CORE to Analytics Backup Copy'
	, @FileName = '{DatabaseName}_{BackupType}_{FileNumber}.{FileExtension}'
	, @Execute = 'Y'
	, @LogToTable = 'Y'

**Comment by Timbleweed** [comment] 2020-07-20 14:07
copy pastes is not working.  back slash in @direcortory caused two back slashes before database name in path

**Comment by olahallengren** [comment] 2020-11-14 21:06
Could you share the full output that you are getting?

**Comment by olahallengren** [comment] 2020-12-05 17:43
@Timbleweed, have you got this working? Did you find out about the issue?

**Comment by olahallengren** [comment] 2021-12-31 21:14
Is this issue still happening?

**Comment by olahallengren** [comment] 2024-11-23 18:28
I am closing this issue as I am not able to reproduce it.

**Closed by olahallengren** 2024-11-23 18:28 UTC
Labels: DatabaseBackup, Bug Report
