### ISSUE TITLE
Deleting Encrypted Backup Files

### ISSUE THREAD

**Issue by NickColebourn** [olahallengren/sql-server-maintenance-solution#669] opened 2022-08-07 16:46 UTC
So this isn't an issue that is likely fixable, but one that probably needs listing on the FAQs. If you encrypt your backup files to disk then xp_delete_file can't read the headers and therefore doesn't delete the files. However it "fails" silently, which means there's no obvious issue until the disk space alerts / runs out. 

A possible workaround would be an additional SQL Agent job that runs a PowerShell script (working on that in my environment now).

**SQL Server version and edition**
Microsoft SQL Server 2019 (RTM-CU16-GDR) (KB5014353) - 15.0.4236.7 (X64)   May 29 2022 15:55:47   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor) 

**Version of the script**
--// Version: 2022-01-02 13:58:13

**Comment by NickColebourn** [comment] 2022-08-08 13:28
This is my PowerShell workaround based on the Ola folder structures. Tested and working as a SQL Agent Job using a PowerShell type. 

$FullBackupRetention = -672
$DiffBackupRetention = -336
$LogBackupRetention = -168

$folders = Get-ChildItem -Path B:\SQLBackups -Recurse -Directory -Filter "FULL"## | Select FullName%{$_.FullName}

foreach ($folder in $folders)
{
    ##$folder.FullName
    Get-ChildItem -Path $folder.FullName -File -Filter "*.bak" | Where-Object{$_.LastWriteTime -lt (Get-Date).AddHours($FullBackupRetention)}  | Remove-Item -Verbose

}


$folders = Get-ChildItem -Path B:\SQLBackups -Recurse -Directory -Filter "DIFF"## | Select FullName%{$_.FullName}

foreach ($folder in $folders)
{
    ##$folder.FullName
    Get-ChildItem -Path $folder.FullName -File -Filter "*.bak" | Where-Object{$_.LastWriteTime -lt (Get-Date).AddHours($DiffBackupRetention)}  | Remove-Item -Verbose

}

$folders = Get-ChildItem -Path B:\SQLBackups -Recurse -Directory -Filter "LOG"## | Select FullName%{$_.FullName}

foreach ($folder in $folders)
{
    ##$folder.FullName
    Get-ChildItem -Path $folder.FullName -File -Filter "*.trn" | Where-Object{$_.LastWriteTime -lt (Get-Date).AddHours($LogBackupRetention)}  | Remove-Item -Verbose

}

**Comment by olahallengren** [comment] 2024-10-28 21:38
> So this isn't an issue that is likely fixable, but one that probably needs listing on the FAQs. If you encrypt your backup files to disk then xp_delete_file can't read the headers and therefore doesn't delete the files. However it "fails" silently, which means there's no obvious issue until the disk space alerts / runs out.

To me this sounds like a bug in SQL Server. Could you try reproducing the same thing using the Maintenance Plans (that is using xp_delete_file)?

**Comment by olahallengren** [comment] 2024-11-23 17:14
@NickColebourn, do you know if it is the same issue with TDE encryption and backup encryption?

**Comment by NickColebourn** [comment] 2024-11-26 10:05
I'm sorry Ola but I'm unable to commit time to testing this now. Feel free to delete the issue.

Regards
Nick Colebourn - DBBI Ltd
Director
Tel: 07949 734 278
Microsoft Certified Master: SQL Server<https://download.microsoft.com/download/7/C/2/7C28964B-E49D-4C4D-A78B-FC0C844FA66B/MCM-SQL.pdf>
Microsoft Certified Solutions Master: SQL Server Data Platform<http://download.microsoft.com/download/3/0/E/30E3CDA4-407E-4893-B070-3827B6F6A586/MCSM_Data_Platform_Datasheet.pdf>
***@***.******@***.***>
http://www.dbbi.co.uk<https://protect-eu.mimecast.com/s/pGliC0g7NcYlo8CWY73q?domain=eur02.safelinks.protection.outlook.com>

**Comment by olahallengren** [comment] 2024-12-14 20:38
I have tested it with TDE as well as with backup encryption, with no issues.

@NickColebourn could you just let me know which type of encryption that you were using?

**Comment by olahallengren** [comment] 2024-12-21 13:10
I am closing this issue, as I am not able to reproduce it. Please write back if you or anyone run into this issue again. I will then reopen the issue.

**Closed by olahallengren** 2024-12-21 13:10 UTC
Labels: DatabaseBackup, Bug Report
