### ISSUE TITLE
DatabaseBackup: Cannot backup to multiple mirrors

### ISSUE THREAD

**Issue by garyhampson** [olahallengren/sql-server-maintenance-solution#213] opened 2019-04-02 19:27 UTC
**Description of the issue**
Getting `The value for the parameter @Directory is not supported` and `The value for the parameter @MirrorDirectory is not supported` errors when attempting to provide more than one mirror directory in the call to the `DatabaseBackup` stored procedure. This part of the validation is raising the error:
```
<snip>
(SELECT COUNT(*) FROM @Directories WHERE Mirror = 0) <> (SELECT COUNT(*) FROM @Directories WHERE Mirror = 1) 
  AND (SELECT COUNT(*) FROM @Directories WHERE Mirror = 1) > 0)
</snip>
```
In my case, `SELECT COUNT(*) FROM @Directories WHERE Mirror = 0` is 1 where `SELECT COUNT(*) FROM @Directories WHERE Mirror = 1` is 2.

**SQL Server version and edition**
Execute ```SELECT @@VERSION```
```
Microsoft SQL Server 2016 (SP2-CU5) (KB4475776) - 13.0.5264.1 (X64) 
	Jan 10 2019 18:51:38 
	Copyright (c) Microsoft Corporation
	Developer Edition (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor)
```
**Version of the script**
```Version: 2019-02-10 10:40:47 ```

**What command are you executing?**
```
EXECUTE dbo.DatabaseBackup
@Databases = 'MYDATABASE',
@Directory = 'Z:\Backups',
@MirrorDirectory = '\\SERVER01\Z$\Backups,\\SERVER02\Z$\Backups',
@BackupType = 'FULL',
@Compress = 'Y',
@CopyOnly = 'Y',
@Encrypt = 'Y',
@LogToTable = 'Y',
@DirectoryStructure = '{BackupType}{DirectorySeparator}{DatabaseName}{DirectorySeparator}',
@AvailabilityGroupDirectoryStructure = '{BackupType}{DirectorySeparator}{DatabaseName}{DirectorySeparator}',
@FileName = '{ServerName}${InstanceName}_{DatabaseName}_{BackupType}_{Partial}_{CopyOnly}_{Year}{Month}{Day}_{Hour}{Minute}{Second}_{FileNumber}.{FileExtension}',
@AvailabilityGroupFileName = '{BackupType}_{ServerName}${InstanceName}_{DatabaseName}_{BackupType}_{Partial}_{CopyOnly}_{Year}{Month}{Day}_{Hour}{Minute}{Second}_{FileNumber}.{FileExtension}',
@EncryptionAlgorithm = 'AES_256',
@ServerCertificate = 'BackupCert',
@Verify = 'Y',
@CheckSum = 'Y';
```
**What output are you getting?**
```
Date and time: 2019-04-02 15:07:32
Server: SQLSERVER
Version: 13.0.5264.1
Edition: Developer Edition (64-bit)
Platform: Windows
Procedure: [DBAdmin].[dbo].[DatabaseBackup]
Parameters: @Databases = 'MYDATABASE', @Directory = 'Z:\Backups', @BackupType = 'FULL', @Verify = 'Y', @CleanupTime = NULL, @CleanupMode = 'AFTER_BACKUP', @Compress = 'Y', @CopyOnly = 'Y', @ChangeBackupType = 'N', @BackupSoftware = NULL, @CheckSum = 'Y', @BlockSize = NULL, @BufferCount = NULL, @MaxTransferSize = NULL, @NumberOfFiles = NULL, @CompressionLevel = NULL, @Description = NULL, @Threads = NULL, @Throttle = NULL, @Encrypt = 'Y', @EncryptionAlgorithm = 'AES_256', @ServerCertificate = 'BackupCert', @ServerAsymmetricKey = NULL, @EncryptionKey = NULL, @ReadWriteFileGroups = 'N', @OverrideBackupPreference = 'N', @NoRecovery = 'N', @URL = NULL, @Credential = NULL, @MirrorDirectory = '\\SERVER01\Z$\Backups,\\SERVER02\Z$\Backups', @MirrorCleanupTime = NULL, @MirrorCleanupMode = 'AFTER_BACKUP', @MirrorURL = NULL, @AvailabilityGroups = NULL, @Updateability = 'ALL', @AdaptiveCompression = NULL, @ModificationLevel = NULL, @LogSizeSinceLastLogBackup = NULL, @TimeSinceLastLogBackup = NULL, @DataDomainBoostHost = NULL, @DataDomainBoostUser = NULL, @DataDomainBoostDevicePath = NULL, @DataDomainBoostLockboxPath = NULL, @DirectoryStructure = '{BackupType}{DirectorySeparator}{DatabaseName}{DirectorySeparator}', @AvailabilityGroupDirectoryStructure = '{BackupType}{DirectorySeparator}{DatabaseName}{DirectorySeparator}', @FileName = '{ServerName}${InstanceName}_{DatabaseName}_{BackupType}_{Partial}_{CopyOnly}_{Year}{Month}{Day}_{Hour}{Minute}{Second}_{FileNumber}.{FileExtension}', @AvailabilityGroupFileName = '{BackupType}_{ServerName}${InstanceName}_{DatabaseName}_{BackupType}_{Partial}_{CopyOnly}_{Year}{Month}{Day}_{Hour}{Minute}{Second}_{FileNumber}.{FileExtension}', @FileExtensionFull = NULL, @FileExtensionDiff = NULL, @FileExtensionLog = NULL, @Init = 'N', @DatabaseOrder = NULL, @DatabasesInParallel = 'N', @LogToTable = 'Y', @Execute = 'Y'
Version: 2019-02-10 10:40:47
Source: https://ola.hallengren.com
	
Msg 50000, Level 16, State 1, Procedure DatabaseBackup, Line 805 [Batch Start Line 0]
The value for the parameter @Directory is not supported.
	
Msg 50000, Level 16, State 1, Procedure DatabaseBackup, Line 814 [Batch Start Line 0]
The value for the parameter @MirrorDirectory is not supported.
	
Msg 50000, Level 16, State 1, Procedure DatabaseBackup, Line 1559 [Batch Start Line 0]
The documentation is available at https://ola.hallengren.com/sql-server-backup.html.
	
Date and time: 2019-04-02 15:07:32
```

**Comment by samot1** [comment] 2019-04-09 09:26
Hi Gary, 

have a look onto my own fork at https://github.com/samot1/sql-server-maintenance-solution/blob/master/DatabaseBackup.sql (Pull Request https://github.com/olahallengren/sql-server-maintenance-solution/pull/197).

We had the same problem and I enhanced the Database Backup by two other mirrors. Furthermore it supports an "asynchron mirroring" (copying the files in another job), which I would prefer, since otherwise your whole backup will fail, when one of the mirror directories is / goes down.

The script in the fork is in production since 3 or 4 years, so it should work well.

**Comment by olahallengren** [comment] 2019-04-27 18:01
DatabaseBackup only supports one mirror.

Specifying multiple directories with a comma in between, means striping in DatabaseBackup:

You can for example do like:
```
EXECUTE dbo.DatabaseBackup
@Databases = 'model',
@Directory = 'C:\Backup, D:\Backup',
@MirrorDirectory = 'E:\Backup, F:\Backup',
@BackupType = 'FULL'
```

**Comment by garyhampson** [comment] 2019-04-27 18:28
Hi Ola,

The use case we were trying was using DatabaseBackup to copy log backups to a new Availability Group as part of a migration strategy for databases that were already being backed up using your scripts. Kinda like a poor man’s log shipping. The idea was that we would mirror the log backups to both the primary and secondary replicas and restore there until we were ready to cut over to the new instances.

**Comment by olahallengren** [comment] 2019-04-27 19:11
There is one thing that is important to be aware of with regards to mirrored backups:

If one of the backup locations (the primary or any of the mirror locations) is not available, then the backup will fail. The more backup locations that you have, the more likely the backup is to fail.

**Comment by olahallengren** [comment] 2019-05-03 18:55
I am closing this issue as it is by design.

**Closed by olahallengren** 2019-05-03 18:55 UTC
Labels: DatabaseBackup, bug_report
