### ISSUE TITLE
Server Name and AAG name now in DB name or path

### ISSUE THREAD

**Issue by MRSKINNMAN** [olahallengren/sql-server-maintenance-solution#341] opened 2020-01-28 17:40 UTC
**Description of the issue**
I downloaded and applied the update for 2020-01-11.  Once I did that my @Directory setting stayed the same however the rest of the path changed

This affected @Directory and @DirectoryStructure as well as @AvailabilityGroupDirectoryStructure and @AvailabilityGroupFileName now include servername and AAG or clustername.

This is a copy (names changed for security) of my code
@Directory = '_\\Backup secure path_\_ServerName_\',
@DirectoryStructure = '{DatabaseName}{DirectorySeparator}{BackupType}',
@FileName =   '{DatabaseName}_{BackupType}_{Year}_{Month}_{Day}_{Hour}{Minute}{Second}.{FileExtension}',
 or AAG

@AvailabilityGroupDirectoryStructure = '{DatabaseName}{DirectorySeparator}{BackupType}',
@AvailabilityGroupFileName = '{DatabaseName}_{BackupType}_{Year}_{Month}_{Day}_{Hour}{Minute}{Second}.{FileExtension}',

Pathing as it was prior to update:
_\\Securebackuplocation_\ServerName or AAG\DatabaseName\DatabaseName_BackupType_YYYYMMDD_HHMMMSS.extension

Pathing after update
_\\Securebackuplocation_\ServerName or AAG\Server or ClusterName$Cluster\DBName\BackupType\ClusterName$Cluster_DBName_YYYYMMDD_HHMMMSS.extension

It seems somehow the server name and or cluster name are now in the path and DB backup name.

**SQL Server version and edition**
Execute ```SELECT @@VERSION```
SQL 2016 (13.0.5598.27) and starting SQL 2019 (15.0.4003.23)

**Version of the script**
Check the header of the stored procedure

Version: 2020-01-14 21:48:14

**What command are you executing?** 
EXECUTE dbo.DatabaseBackup 

**What output are you getting?**
See above

**Comment by olahallengren** [comment] 2020-02-01 17:37
The cluster name and availability group name has been part of the directory path, for databases in availability groups, for a long time.

20 May 2012
"Added cluster name and availability group name to the backup directory and filename, for databases in availability groups."
https://ola.hallengren.com/versions.html

The reason for this change, is that when you back up to a file share, then the backups should go into the same directory after a failover.

To make it consistent, I made it the same for the file names (this was a later change).

If this is not what you want, you could set ```@AvailabilityGroupDirectoryStructure``` and ```@AvailabilityGroupFileName```, to the same values as ```@DirectoryStructure``` and ```@FileName```.

**Comment by MRSKINNMAN** [comment] 2020-02-02 07:12
Yes “if” you put the parameters in the pathing however in my included scripting I had not in the past nor did I change my code the only difference was the new update I applied.  Then suddenly the pathing changed.

Erik Skinner
________________________________

**Comment by olahallengren** [comment] 2020-02-23 16:22
It is very rarely that I change the defaults or do any breaking changes, but in this case I did. I am sorry that this caused problems for you.

**Comment by MRSKINNMAN** [comment] 2020-02-25 20:13
Thank you for taking the time to look at this, I know you have provided this enormous support for free and even maintain it.

Is it fixed for me or is this the new standard?  I just need to know I have an automated restore for bug testing that I need to know the pathing for production.

Thank you again.

Erik Skinner

________________________________

**Comment by olahallengren** [comment] 2020-03-01 18:35
As it works now is the default since 20 May 2012.

In 23 May 2018 I made the directory paths configurable.

I have no plans to do any more changes to this.

**Comment by MRSKINNMAN** [comment] 2020-03-02 20:49
I do not want to be the one scolded for poking the bear.  I reread your Backup documentation<https://ola.hallengren.com/sql-server-backup.html> (The link is so you know I am referencing your instructions) and there is already a variable\ identifier for {ServerName}, {InstanceName}, etc but not one for AAG or Clustername.

In my scripting I put in the following:

/* Database backup full */
EXECUTE master.dbo.DatabaseBackup
@Databases = 'DatabaseName',
@BackupType = 'FULL',
@LogToTable = 'Y',
@Directory = '\\BackupServer\BackupShare\SQL_Daily\ClusterName\',
@AvailabilityGroupDirectoryStructure = '{DatabaseName}{DirectorySeparator}{BackupType}',
@AvailabilityGroupFileName = '{DatabaseName}_{BackupType}_{Year}_{Month}_{Day}_{Hour}{Minute}{Second}.{FileExtension}',
@Verify = 'Y',
@Compress = 'Y',
@CleanupTime = 73,
@CleanupMode = 'AFTER_BACKUP';


When I look at the output pathing I get:

\\BackupServer\BackupShare\SQL_Daily\ClusterName\ServerName (which I did not put in)\DBNAme\FULL\ServerName(Again I did not put in)_DB_NAME_FULL_20200226_165412.bak.

Again not to be disagreeable but up till a few versions ago the ServerName was  an entered choice as shown in my @DirectoryStructure line which I use in non AAG servers.  This structure would path correctly

When I run the backup on a single server I have not updated I use the following script:

/* Database backup full */
EXECUTE master.dbo.DatabaseBackup
@Databases = 'RenovoDatabase',
@BackupType = 'FULL',
@LogToTable = 'Y',
@Directory = '\\mncvms01\sqlbackups$\SQL_Daily\',
@DirectoryStructure = '{ServerName}{DirectorySeparator}{DatabaseName}{DirectorySeparator}{BackupType}',
@FileName = '{DatabaseName}_{BackupType}_{Year}_{Month}_{Day}_{Hour}{Minute}{Second}.{FileExtension}',
@Verify = 'Y',
@Compress = 'Y',
@CleanupTime = 73,
@CleanupMode = 'AFTER_BACKUP';

And receive the following output pathing:
\\BackupServer\BackupShare\SQL_Daily\ServerName (which I put in)\DBName\FULL\DBName(Note no ServerName)_FULL_2020_03_02_142632.bak

Something changed in the "default" settings that is automatically putting in the ServerName and or ClusterName$ServerName even though I did outline my @DataStructure or@AvailabilityGroupDirectoryStructure in the updated version NOT to have the servername.  This especially is problematic in AAG where you can have multiple servers and really refer to the lot as a AAG name.

I understand that the default @DirectoryStructure and @AvailabilityGroupDirectoryStructure are {ServerName}${InstanceName}{DirectorySeparator}{DatabaseName}{DirectorySeparator}{BackupType}_{Partial}_{CopyOnly} and {ClusterName}${AvailabilityGroupName}{DirectorySeparator}{DatabaseName}{DirectorySeparator}{BackupType}_{Partial}_{CopyOnly} respectively and for @FileName and @AvailabilityGroupFileName   {ServerName}${InstanceName}_{DatabaseName}_{BackupType}_{Partial}_{CopyOnly}_{Year}{Month}{Day}_{Hour}{Minute}{Second}_{FileNumber}.{FileExtension} and  {ClusterName}${AvailabilityGroupName}_{DatabaseName}_{BackupType}_{Partial}_{CopyOnly}_{Year}{Month}{Day}_{Hour}{Minute}{Second}_{FileNumber}.{FileExtension} respectively.

I was under the understanding by me setting my preferences this would overwrite the default.

Thank you for your continued support and feed back.

Erik Skinner

________________________________

**Comment by olahallengren** [comment] 2020-03-02 22:13
@MRSKINNMAN, thank you for the feedback. I will look at the code again, and try to understand what has happened.

**Comment by olahallengren** [comment] 2024-11-24 12:04
@MRSKINNMAN, I have been testing this again, and in my testing it works as it should. I have not been able to reproduce the issue.

If you are still experiencing issues, please let me know.

**Comment by MRSKINNMAN** [comment] 2024-11-24 20:35
Thank you for looking into this issue.  Over the year I think I figured out the issue. If I run the backup from the aag I get the aag path and settings. If I run them process from the individual servers it uses a different path.

Thank you for your time.

Erik Skinner

Erik Skinner
________________________________

**Comment by olahallengren** [comment] 2024-11-24 20:49
> If I run the backup from the aag I get the aag path and settings. If I run them process from the individual servers it uses a different path.

Could you elaborate a bit more on how you are running it in these two scenarios?

The stored procedure have to run on the local servers. Then it is using different paths based on if the databases are in availability groups or not.

**Comment by olahallengren** [comment] 2024-12-14 20:29
I am am not able to reproduce the issue. I am closing it now. Please reopen it if you start experiencing the issue again.

**Closed by olahallengren** 2024-12-14 20:29 UTC
Labels: DatabaseBackup, Bug Report
